""" curent user preference

Revision ID: 0102c9ae4f57
Revises: 0f909120d0a0
Create Date: 2020-12-16 17:23:07.626882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0102c9ae4f57'
down_revision = '0f909120d0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curent_user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=True),
    sa.Column('preference_user_id', sa.Integer(), nullable=True),
    sa.Column('current_user_preference', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['preference.id'], ),
    sa.ForeignKeyConstraint(['preference_user_id'], ['preference_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curent_user_preference')
    # ### end Alembic commands ###
