"""empty message

Revision ID: 0f909120d0a0
Revises: d0ffeabce1a8
Create Date: 2020-12-11 00:59:21.127122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f909120d0a0'
down_revision = 'd0ffeabce1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script', 'file_name')
    # ### end Alembic commands ###
