"""empty message

Revision ID: 2578fbfa7840
Revises: edd338c728cd
Create Date: 2020-12-11 00:43:36.812288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2578fbfa7840'
down_revision = 'edd338c728cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'file_name')
    # ### end Alembic commands ###
