"""add resource model 

Revision ID: 417d22f291c9
Revises: 4a986341ffdf
Create Date: 2020-12-18 18:48:04.541293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417d22f291c9'
down_revision = '4a986341ffdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['preference.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_resource')
    op.drop_table('resources')
    # ### end Alembic commands ###
