"""add resource model 

Revision ID: 48c3ba7087bf
Revises: 7b2d0c767271
Create Date: 2020-12-18 18:49:50.193646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c3ba7087bf'
down_revision = '7b2d0c767271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference_resource', sa.Column('resource_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'preference_resource', 'resources', ['resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preference_resource', type_='foreignkey')
    op.drop_column('preference_resource', 'resource_id')
    # ### end Alembic commands ###
