""" curent user preference add name

Revision ID: 4a986341ffdf
Revises: 0102c9ae4f57
Create Date: 2020-12-16 20:16:30.095045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a986341ffdf'
down_revision = '0102c9ae4f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curent_user_preference', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('preference', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('curent_user_preference', 'name')
    # ### end Alembic commands ###
