"""empty message

Revision ID: 6680a05460f8
Revises: 8ada071ad9e7
Create Date: 2020-12-01 16:45:42.337933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6680a05460f8'
down_revision = '8ada071ad9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference_module', sa.Column('preference_id', sa.Integer(), nullable=False))
    op.drop_constraint('preference_module_Preference_id_fkey', 'preference_module', type_='foreignkey')
    op.create_foreign_key(None, 'preference_module', 'preference', ['preference_id'], ['id'])
    op.drop_column('preference_module', 'Preference_id')
    op.add_column('preference_script', sa.Column('preference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'preference_script', 'preference', ['preference_id'], ['id'])
    op.add_column('preference_user', sa.Column('preference_id', sa.Integer(), nullable=True))
    op.drop_constraint('preference_user_Preference_id_fkey', 'preference_user', type_='foreignkey')
    op.create_foreign_key(None, 'preference_user', 'preference', ['preference_id'], ['id'])
    op.drop_column('preference_user', 'Preference_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference_user', sa.Column('Preference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'preference_user', type_='foreignkey')
    op.create_foreign_key('preference_user_Preference_id_fkey', 'preference_user', 'preference', ['Preference_id'], ['id'])
    op.drop_column('preference_user', 'preference_id')
    op.drop_constraint(None, 'preference_script', type_='foreignkey')
    op.drop_column('preference_script', 'preference_id')
    op.add_column('preference_module', sa.Column('Preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'preference_module', type_='foreignkey')
    op.create_foreign_key('preference_module_Preference_id_fkey', 'preference_module', 'preference', ['Preference_id'], ['id'])
    op.drop_column('preference_module', 'preference_id')
    # ### end Alembic commands ###
