"""empty message

Revision ID: 8ada071ad9e7
Revises: de940cb643c6
Create Date: 2020-12-01 16:42:13.355945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ada071ad9e7'
down_revision = 'de940cb643c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module', 'file_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('preference_module', sa.Column('Preference_id', sa.Integer(), nullable=False))
    op.add_column('preference_module', sa.Column('module_id', sa.Integer(), nullable=False))
    op.drop_constraint('preference_module_preference_script_id_fkey', 'preference_module', type_='foreignkey')
    op.create_foreign_key(None, 'preference_module', 'preference', ['Preference_id'], ['id'])
    op.create_foreign_key(None, 'preference_module', 'module', ['module_id'], ['id'])
    op.drop_column('preference_module', 'preference_script_id')
    op.add_column('preference_script', sa.Column('script_id', sa.Integer(), nullable=True))
    op.drop_constraint('preference_script_preference_script_id_fkey', 'preference_script', type_='foreignkey')
    op.create_foreign_key(None, 'preference_script', 'script', ['script_id'], ['id'])
    op.drop_column('preference_script', 'preference_script_id')
    op.add_column('preference_user', sa.Column('Preference_id', sa.Integer(), nullable=True))
    op.alter_column('preference_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('preference_user_preference_id_fkey', 'preference_user', type_='foreignkey')
    op.create_foreign_key(None, 'preference_user', 'preference', ['Preference_id'], ['id'])
    op.drop_column('preference_user', 'preference_id')
    op.alter_column('script', 'file_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script', 'file_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('preference_user', sa.Column('preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'preference_user', type_='foreignkey')
    op.create_foreign_key('preference_user_preference_id_fkey', 'preference_user', 'preference', ['preference_id'], ['id'])
    op.alter_column('preference_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('preference_user', 'Preference_id')
    op.add_column('preference_script', sa.Column('preference_script_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'preference_script', type_='foreignkey')
    op.create_foreign_key('preference_script_preference_script_id_fkey', 'preference_script', 'script', ['preference_script_id'], ['id'])
    op.drop_column('preference_script', 'script_id')
    op.add_column('preference_module', sa.Column('preference_script_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'preference_module', type_='foreignkey')
    op.drop_constraint(None, 'preference_module', type_='foreignkey')
    op.create_foreign_key('preference_module_preference_script_id_fkey', 'preference_module', 'module', ['preference_script_id'], ['id'])
    op.drop_column('preference_module', 'module_id')
    op.drop_column('preference_module', 'Preference_id')
    op.alter_column('module', 'file_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
